### ISSUE TITLE
Renamed TF files

### ISSUE THREAD

**Issue by CodeDweller** [awjuliani/DNN-Sentiment#1]
Hi,

I wanted to mess around with your code a bit, to try something out, but I stumbled upon a couple of errors.

> Traceback (most recent call last):
>   File "train_rnn.py", line 2, in <module>
>     from tensorflow.models.rnn import rnn, rnn_cell
> ImportError: No module named models.rnn
> 

Instead of `from tensorflow.models.rnn import rnn, rnn_cell` it should be `from tensorflow.contrib import rnn`.

Also this:

> Traceback (most recent call last):
>   File "train_rnn.py", line 23, in <module>
>     x_train, y_train, vocabulary, vocabulary_inv = data_helpers.load_data()
>   File "/home/ljuba/Project/RNNClassification/DNN-Sentiment/data_helpers.py", line 108, in load_data
>     sentences, labels = load_data_and_labels()
>   File "/home/ljuba/Project/RNNClassification/DNN-Sentiment/data_helpers.py", line 41, in load_data_and_labels
>     x_text = list(open("./trainUNK.txt", "r").readlines())
> IOError: [Errno 2] No such file or directory: './trainUNK.txt'
> 

In data_helpers.py on line 41, what is './trainUNK.txt' for?

**Comment by awjuliani** [comment]
Thanks for pointing these out. I've updated the rnn import, and removed the "trainUNK.txt" line.

**Comment by CodeDweller** [comment]
You need to fix train_rnn.py also, but otherwise it works. Thanks!

**Comment by CodeDweller** [comment]
Sorry, didn't want to create another issue for this.

I get the following error when I run train_rnn.py:

> Traceback (most recent call last):
>   File "train_rnn.py", line 34, in <module>
>     final_embeddings = w2v.runWord2Vec()
>   File "/home/ljuba/Project/RNNClassification/DNN-Sentiment/word2vec.py", line 101, in runWord2Vec
>     num_sampled, self.vocabulary_size))
>   File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/nn_impl.py", line 1115, in nce_loss
>     name=name)
>   File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/nn_impl.py", line 974, in _compute_sampled_logits
>     array_ops.reshape(true_w, new_true_w_shape))
>   File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/math_ops.py", line 357, in multiply
>     return gen_math_ops._mul(x, y, name)
>   File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gen_math_ops.py", line 1625, in _mul
>     result = _op_def_lib.apply_op("Mul", x=x, y=y, name=name)
>   File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/op_def_library.py", line 522, in apply_op
>     inferred_from[input_arg.type_attr]))
> TypeError: Input 'y' of 'Mul' Op has type float32 that does not match type int32 of argument 'x'.

I'm guessing that `num_sampled` in word2vec.py on line 101 needs to be converted to float32. Just a speculation, hadn't tried it yet...

**Comment by awjuliani** [comment]
Hi CodeDweller, I am sorry the code is giving you problems. This was a class project from a year ago, and unfortunately I am no longer maintaining this repo. 

If you are able to find something that works, and would like to submit a pull request, I would be more happy to incorporate it though.

**Comment by CodeDweller** [comment]
Hi, no problem at all. I'm just glad that I found some code that I can learn on being that I'm just getting started in the field and I'm interested in the practical aspect of RNNs.

I'll try to fix the code if I can, and will submit a pull request if I'm successful.
